project:
  type: website

website:
  title: "Stone Lab UVP Guide"
  author: "Alex Barth"
  date: "5/26/2022"
  sidebar:
    style: 'docked'
    search: true
    contents:
      - index.qmd
    favicon: favicon_black.ico


format:
  html:
    theme: sandstone
    css: alex_style.css

editor: visual

