project:
  type: website

website:
  title: "StoneLabUVPGuide"
  author: "Jane Doe"
  date: "5/26/2022"
  sidebar:
    style: 'docked'
    search: true
    contents:
      - index.qmd


format:
  html:
    theme: sandstone
    css: alex_style.css

editor: visual

